spring:
  cloud:
    gateway:
      routes:

        - id: packageService
          uri: http://localhost:9098/package
          predicates:
            - Path=/package/**
          filters:
            - AuthenticationFilter

        - id: guideService
          uri: http://localhost:9095/guide
          predicates:
            - Path=/guide/**
          filters:
            - AuthenticationFilter

        - id: hotelService
          uri: http://localhost:9097/hotel
          predicates:
            - Path=/hotel/**
          filters:
            - AuthenticationFilter

        - id: vehicleService
          uri: http://localhost:9096/vehicle
          predicates:
            - Path=/vehicle/**
          filters:
            - AuthenticationFilter

        - id: authService
          uri: http://localhost:9093/auth
          predicates:
            - Path=/auth/**
